CREATE TABLE USER_TESTFIELD (
    USER_NICK VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(30) BINARY NOT NULL,
    DATE_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USER_TESTFIELD (
    USER_NICK,
    PASSWORD
) VALUES (
    'andriy',
    'andriy'
);

INSERT INTO USER_INFO (
	USER_NICK,
    EMAIL
) VALUES (
	'andriy',
    'andsei91@gmail.com'
);

-- CREATE TABLE CONNECTIONS (
--     TOKEN VARCHAR(100),
--     USER_NICK VARCHAR(30),
--     LAST_TIME DATE,
--     CONSTRAINT FOREIGN KEY(USER_NICK) REFERENCES USER_TESTFIELD(USER_NICK)
-- );

CREATE TABLE USER_INFO (
    USER_NICK VARCHAR(30) PRIMARY KEY,
    EMAIL VARCHAR(80),
    CONSTRAINT FOREIGN KEY(USER_NICK) REFERENCES USER_TESTFIELD(USER_NICK)
);

CREATE TABLE TAG (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE MANUAL (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    USER_NICK VARCHAR(30) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    VISIBILITY INT(2) NOT NULL DEFAULT 0,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_LAST_MOD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATE_CURRENT INT(2) NOT NULL DEFAULT 0,
    CONSTRAINT FOREIGN KEY(USER_NICK) REFERENCES USER_TESTFIELD(USER_NICK)
);

CREATE TABLE REL_TAG_MANUAL (
	TAG VARCHAR(60) BINARY,
    MANUAL VARCHAR(60) BINARY,
    CONSTRAINT PRIMARY KEY (TAG, MANUAL),
    CONSTRAINT FOREIGN KEY(TAG) REFERENCES TAG(ID),
    CONSTRAINT FOREIGN KEY(MANUAL) REFERENCES MANUAL(ID)
);

CREATE TABLE MANUAL_PAGE (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    MANUAL VARCHAR(60) BINARY NOT NULL,
    PAGE_ORDER INT(5) NOT NULL,
    CONSTRAINT FOREIGN KEY(MANUAL) REFERENCES MANUAL(ID)
);

CREATE TABLE MANUAL_ROW (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    MANUAL_PAGE VARCHAR(60) BINARY NOT NULL,
    ROW_ORDER INT(5) NOT NULL,
    CONSTRAINT FOREIGN KEY(MANUAL_PAGE) REFERENCES MANUAL_PAGE(ID)
);

CREATE TABLE WIDTH_TYPE (
    WIDTH_TYPE INT(2) PRIMARY KEY,
    DESCRIPTION VARCHAR(60) NOT NULL
);

INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	1,
    'Phones'
);

INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	2,
    'Tablets'
);

INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	3,
    'Default'
);


INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	4,
    'Large display'
);

CREATE TABLE BLOCK_WIDTH_TYPE (
	WIDTH_TYPE INT(2) NOT NULL,
    MANUAL_BLOCK VARCHAR(60) BINARY NOT NULL,
    CONSTRAINT PRIMARY KEY(WIDTH_TYPE, MANUAL_BLOCK),
    CONSTRAINT FOREIGN KEY(WIDTH_TYPE) REFERENCES WIDTH_TYPE(WIDTH_TYPE),
    CONSTRAINT FOREIGN KEY(MANUAL_BLOCK) REFERENCES MANUAL_BLOCK(ID)
);

CREATE TABLE MANUAL_BLOCK (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    MANUAL_ROW VARCHAR(60) BINARY NOT NULL,
    BLOCK_ORDER INT(5) NOT NULL,
    CONTENT TEXT,
    WIDTH INT(3),
    CONSTRAINT FOREIGN KEY(MANUAL_ROW) REFERENCES MANUAL_ROW(ID)
);

