CREATE TABLE USER_TESTFIELD (
	USER_NICK VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(30),
    DATE_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USER_TESTFIELD (
	USER_NICK,
    PASSWORD
) VALUES (
	'andriy',
    'andriy'
);

CREATE TABLE CONNECTIONS (
	TOKEN VARCHAR(100),
    USER_NICK VARCHAR(30),
    LAST_TIME DATE,
    CONSTRAINT FOREIGN KEY(USER_NICK) REFERENCES USER_TESTFIELD(USER_NICK)
);

