CREATE TABLE USER_TESTFIELD (
    USER_NICK VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(30) BINARY NOT NULL,
    DATE_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USER_TESTFIELD (
    USER_NICK,
    PASSWORD
) VALUES (
    'andriy',
    'andriy'
);

CREATE TABLE USER_INFO (
    USER_NICK VARCHAR(30) PRIMARY KEY,
    EMAIL VARCHAR(80),
    CONSTRAINT FOREIGN KEY(USER_NICK) REFERENCES USER_TESTFIELD(USER_NICK)
);

INSERT INTO USER_INFO (
	USER_NICK,
    EMAIL
) VALUES (
	'andriy',
    'andsei91@gmail.com'
);

CREATE TABLE user_conf (
	user_nick VARCHAR(30) PRIMARY KEY,
    CONSTRAINT FOREIGN KEY(user_nick) REFERENCES user_testfield(user_nick)
);

-- CREATE TABLE CONNECTIONS (
--     TOKEN VARCHAR(100),
--     USER_NICK VARCHAR(30),
--     LAST_TIME DATE,
--     CONSTRAINT FOREIGN KEY(USER_NICK) REFERENCES USER_TESTFIELD(USER_NICK)
-- );

CREATE TABLE TAG (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE MANUAL (
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    USER_NICK VARCHAR(30) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    VISIBILITY INT(2) NOT NULL DEFAULT 0,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_LAST_MOD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CURRENT_STATE INT(2) NOT NULL DEFAULT 0,
    CONSTRAINT FOREIGN KEY(USER_NICK) REFERENCES USER_TESTFIELD(USER_NICK)
);

CREATE TABLE manual_conf (
	manual INT(11) PRIMARY KEY,
    manual_background VARCHAR(255) NOT NULL DEFAULT 'none',
    font_color INT(11) NOT NULL,
    font_family INT(11) NOT NULL,
    CONSTRAINT FOREIGN KEY(id) REFERENCES manual(id),
	CONSTRAINT FOREIGN KEY(font_color) REFERENCES font_color(id),
    CONSTRAINT FOREIGN KEY(font_family) REFERENCES font_family(id)
);

CREATE TABLE REL_TAG_MANUAL (
	TAG VARCHAR(60) BINARY,
    MANUAL INT(11),
    CONSTRAINT PRIMARY KEY (TAG, MANUAL),
    CONSTRAINT FOREIGN KEY(TAG) REFERENCES TAG(ID),
    CONSTRAINT FOREIGN KEY(MANUAL) REFERENCES MANUAL(ID)
);

CREATE TABLE MANUAL_PAGE (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    MANUAL INT(11) NOT NULL,
    PAGE_ORDER INT(5) NOT NULL,
    CONSTRAINT FOREIGN KEY(MANUAL) REFERENCES MANUAL(ID)
);

CREATE TABLE MANUAL_ROW (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    MANUAL_PAGE VARCHAR(60) BINARY NOT NULL,
    ROW_ORDER INT(5) NOT NULL,
    CONSTRAINT FOREIGN KEY(MANUAL_PAGE) REFERENCES MANUAL_PAGE(ID)
);

CREATE TABLE WIDTH_TYPE (
    WIDTH_TYPE INT(2) PRIMARY KEY,
    DESCRIPTION VARCHAR(60) NOT NULL
);

INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	1,
    'Phones'
);

INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	2,
    'Tablets'
);

INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	3,
    'Default'
);


INSERT INTO WIDTH_TYPE(
	WIDTH_TYPE,
    DESCRIPTION
) VALUES (
	4,
    'Large display'
);

CREATE TABLE MANUAL_BLOCK (
	ID VARCHAR(60) BINARY PRIMARY KEY,
    MANUAL_ROW VARCHAR(60) BINARY NOT NULL,
    BLOCK_ORDER INT(5) NOT NULL,
    CONTENT TEXT,
    CONSTRAINT FOREIGN KEY(MANUAL_ROW) REFERENCES MANUAL_ROW(ID)
);

CREATE TABLE REL_BLOCK_WIDTH_TYPE (
	WIDTH_TYPE INT(2) NOT NULL,
    MANUAL_BLOCK VARCHAR(60) BINARY NOT NULL,
    AMOUNT INT(4),
    CONSTRAINT PRIMARY KEY(WIDTH_TYPE, MANUAL_BLOCK),
    CONSTRAINT FOREIGN KEY(WIDTH_TYPE) REFERENCES WIDTH_TYPE(WIDTH_TYPE),
    CONSTRAINT FOREIGN KEY(MANUAL_BLOCK) REFERENCES MANUAL_BLOCK(ID)
);

CREATE TABLE FONT_FAMILY(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    FONT_NAME VARCHAR(100) NOT NULL,
    CSS_STYLE VARCHAR(255) NOT NULL
);

INSERT INTO FONT_FAMILY(
	CSS_STYLE,
    FONT_NAME
) VALUES (
	'"Orbitron", sans-serif',
    'Orbitron'
);

CREATE TABLE FONT_COLOR (
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    R INT(3) NOT NULL,
    G INT(3) NOT NULL,
    B INT(3) NOT NULL
);

