DROP TABLE REL_TAG_MANUAL;
DROP TABLE TAG;
DROP TABLE REL_BLOCK_WIDTH_TYPE;
DROP TABLE WIDTH_TYPE;
DROP TABLE MANUAL_BLOCK;
DROP TABLE MANUAL_ROW;
DROP TABLE MANUAL_PAGE;
DROP TABLE MANUAL;
DROP TABLE USER_INFO;
DROP TABLE USER_TESTFIELD;

COMMIT;