package model.bean;
// Generated 18-nov-2016 19:09:37 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BlockWidthType generated by hbm2java
 */
@Entity
@Table(name = "block_width_type",
         catalog = "testfield"
)
public class BlockWidthType implements java.io.Serializable {

    private BlockWidthTypeId id;
    private WidthType widthType;

    public BlockWidthType() {
    }

    public BlockWidthType(BlockWidthTypeId id, WidthType widthType) {
        this.id = id;
        this.widthType = widthType;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "widthType", column = @Column(name = "WIDTH_TYPE", nullable = false))
        , 
        @AttributeOverride(name = "manualBlock", column = @Column(name = "MANUAL_BLOCK", nullable = false, length = 60))})
    public BlockWidthTypeId getId() {
        return this.id;
    }

    public void setId(BlockWidthTypeId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WIDTH_TYPE", nullable = false, insertable = false, updatable = false)
    public WidthType getWidthType() {
        return this.widthType;
    }

    public void setWidthType(WidthType widthType) {
        this.widthType = widthType;
    }

}
