package model.bean;
// Generated 03-ago-2016 18:40:01 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConnectionsId generated by hbm2java
 */
@Embeddable
public class ConnectionsId  implements java.io.Serializable {


     private String token;
     private String userNick;

    public ConnectionsId() {
    }

    public ConnectionsId(String token, String userNick) {
       this.token = token;
       this.userNick = userNick;
    }
   


    @Column(name="TOKEN", nullable=false)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }


    @Column(name="USER_NICK", nullable=false, length=20)
    public String getUserNick() {
        return this.userNick;
    }
    
    public void setUserNick(String userNick) {
        this.userNick = userNick;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConnectionsId) ) return false;
		 ConnectionsId castOther = ( ConnectionsId ) other; 
         
		 return ( (this.getToken()==castOther.getToken()) || ( this.getToken()!=null && castOther.getToken()!=null && this.getToken().equals(castOther.getToken()) ) )
 && ( (this.getUserNick()==castOther.getUserNick()) || ( this.getUserNick()!=null && castOther.getUserNick()!=null && this.getUserNick().equals(castOther.getUserNick()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getToken() == null ? 0 : this.getToken().hashCode() );
         result = 37 * result + ( getUserNick() == null ? 0 : this.getUserNick().hashCode() );
         return result;
   }   


}


