package model.bean;
// Generated 11-nov-2016 19:12:17 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.beans.Transient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import util.BeanValidator;
import util.enums.BlockWidthTypeEnum;
import util.exceptions.BeanException;

/**
 * ManualBlock generated by hbm2java
 */
@Entity
@Table(name = "manual_block",
         catalog = "testfield"
)
public class ManualBlock implements java.io.Serializable {

    private String id;
    @JsonBackReference
    private ManualRow manualRow;
    private int order;
    private String content;
    private int width;

    public ManualBlock() {
    }

    public ManualBlock(String id, ManualRow manualRow, int order, int width) {
        this.id = id;
        this.manualRow = manualRow;
        this.order = order;
        this.width = width;
    }

    public ManualBlock(String id, ManualRow manualRow, int order, String content, int width) {
        this.id = id;
        this.manualRow = manualRow;
        this.order = order;
        this.content = content;
        this.width = width;
    }

    @Id

    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "ID", unique = true, nullable = false, length = 60)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MANUAL_ROW", nullable = false)
    public ManualRow getManualRow() {
        return this.manualRow;
    }

    public void setManualRow(ManualRow manualRow) {
        this.manualRow = manualRow;
    }

    @Column(name = "BLOCK_ORDER", nullable = false)
    public int getOrder() {
        return this.order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    @Column(name = "CONTENT", length = 65535)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) throws BeanException {
        BeanValidator.validateLength(content, 65535, "Content");
        this.content = content;
    }

    @Column(name = "WIDTH", nullable = false)
    public int getWidth() {
        return this.width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

}
