package model.bean;
// Generated 10-nov-2016 22:20:57 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag",
        catalog = "testfield"
)
public class Tag implements java.io.Serializable {

    private String id;
    private String description;
    @JsonBackReference
    private Set<Manual> manuals = new HashSet<>(0);

    public Tag() {
    }

    public Tag(String id, String description) {
        this.id = id;
        this.description = description;
    }

    public Tag(String id, String description, Set<Manual> manuals) {
        this.id = id;
        this.description = description;
        this.manuals = manuals;
    }

    @Id

    @Column(name = "ID", unique = true, nullable = false, length = 60)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "DESCRIPTION", nullable = false)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "rel_tag_manual", catalog = "testfield", joinColumns = {
        @JoinColumn(name = "TAG", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "MANUAL", nullable = false, updatable = false)})
    public Set<Manual> getManuals() {
        return this.manuals;
    }

    public void setManuals(Set<Manual> manuals) {
        this.manuals = manuals;
    }

}
