package model.bean;
// Generated 06-nov-2016 19:31:10 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import util.BeanValidator;
import util.exceptions.BeanException;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info",
         catalog = "testfield"
)
public class UserInfo implements java.io.Serializable {

    private String userNick;
    private String email;

    public UserInfo() {
    }

    public UserInfo(String userNick) {
        this.userNick = userNick;
    }

    public UserInfo(String userNick, String email) {
        this.userNick = userNick;
        this.email = email;
    }

    @Id

    @Column(name = "USER_NICK", unique = true, nullable = false, length = 30)
    public String getUserNick() {
        return this.userNick;
    }

    public void setUserNick(String userNick) throws BeanException {
        BeanValidator.validateLength(userNick, 30, "User");
        this.userNick = userNick;
    }

    @Column(name = "EMAIL", length = 80)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) throws BeanException {
        BeanValidator.validateLength(email, 80, "Email");
        this.email = email;
    }

}
