package model.bean;
// Generated 18-nov-2016 19:09:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import util.BeanValidator;
import util.exceptions.BeanException;

/**
 * WidthType generated by hbm2java
 */
@Entity
@Table(name = "width_type",
         catalog = "testfield"
)
public class WidthType implements java.io.Serializable {

    private int widthType;
    private String description;
    private Set<BlockWidthType> blockWidthTypes = new HashSet<BlockWidthType>(0);

    public WidthType() {
    }

    public WidthType(int widthType, String description) {
        this.widthType = widthType;
        this.description = description;
    }

    public WidthType(int widthType, String description, Set<BlockWidthType> blockWidthTypes) {
        this.widthType = widthType;
        this.description = description;
        this.blockWidthTypes = blockWidthTypes;
    }

    @Id

    @Column(name = "WIDTH_TYPE", unique = true, nullable = false)
    public int getWidthType() {
        return this.widthType;
    }

    public void setWidthType(int widthType) {
        this.widthType = widthType;
    }

    @Column(name = "DESCRIPTION", nullable = false, length = 60)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) throws BeanException {
        BeanValidator.validateLength(description, 60, "Description");
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "widthType")
    public Set<BlockWidthType> getBlockWidthTypes() {
        return this.blockWidthTypes;
    }

    public void setBlockWidthTypes(Set<BlockWidthType> blockWidthTypes) {
        this.blockWidthTypes = blockWidthTypes;
    }

}
